### ISSUE TITLE
Please show only the items selected in the summary

### ISSUE THREAD

**Issue by sparda2** [wenbolovesnz/ReactWithWebpackStarter#16]
Instead of showing all the products in the order summary, can you please show only the items selected by the customer so that they only see what they ordered? 
This will make it more clear for customers plus will make the size of the table smaller and better looking in orders page.
When the user has not selected any products then you still show the Summary section with the title and total = $0
Thanks :)

**Comment by wenbolovesnz** [comment]
Good idea and will do

**Comment by sparda2** [comment]
cool. I thought you were asleep.
Go on facebook :)

Regards

Jose Velez

**Comment by wenbolovesnz** [comment]
done
